# Generated by Django 5.0.6 on 2024-07-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('s', 'Science'), ('a', 'Arts'), ('f', 'Fiction'), ('d', 'Drama')], max_length=10)),
            ],
        ),
    ]
